services:
  eureka-server:
    build: ./m4-eureka-server
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
      - EUREKA_CLIENT_REGISTER-WITH-EUREKA=false
      - EUREKA_CLIENT_FETCH-REGISTRY=false
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
    networks:
      - mi-red-backend

  game-service:
    build: ./m3-game-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@host.docker.internal:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=SYSTEM
      - SPRING_DATASOURCE_PASSWORD=86377341Israel
    depends_on:
      - eureka-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mi-red-backend

  user-service:
    build: ./m2-user-service
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@host.docker.internal:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=SYSTEM
      - SPRING_DATASOURCE_PASSWORD=86377341Israel
    depends_on:
      - eureka-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mi-red-backend

  review-service:
    build: ./m1-review-service
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@host.docker.internal:1521/XEPDB1
      - SPRING_DATASOURCE_USERNAME=SYSTEM
      - SPRING_DATASOURCE_PASSWORD=86377341Israel
    depends_on:
      - eureka-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - mi-red-backend

networks:
  mi-red-backend:
    driver: bridge
